language: rust

branches:
  only:
  - master
  # Github release tags (for example "v0.9" or "v0.9.1").
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  # Branch names endings with "-release" (for example "0.9.0-release").
  - /-release$/

rust:
- 1.30.0

env:
  global:
  - CARGO_INCREMENTAL=1
  - DEADLINKS_VERS=0.3.0

cache:
  - cargo

dist: trusty

install:
- cargo deadlinks -V | grep $DEADLINKS_VERS || cargo install cargo-deadlinks --vers $DEADLINKS_VERS --force
- rustup component add rustfmt-preview
- rustfmt -V
- rustup component add clippy-preview
- cargo clippy -V

script:
- cargo fmt -- --check
- cargo check
- cargo clippy -- -D warnings
- cargo test --tests
- cargo test --doc
- cargo run --example ed25519_dalek > /dev/null
- cargo clean --doc && cargo doc --all-features --no-deps && cargo deadlinks --dir target/doc
